name: API Validation Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código
        uses: actions/checkout@v4

      - name: 2. Construir y Levantar
        # AQUÍ ESTÁ EL CAMBIO: "docker compose" en lugar de "docker-compose"
        run: docker compose up -d --build

      - name: 3. Esperar a que la API responda
        run: |
          for i in {1..10}; do
            if curl -s http://localhost/health | grep "ok"; then
              echo "API Online!"
              exit 0
            fi
            echo "Esperando API..."
            sleep 3
          done
          exit 1

      - name: 4. Prueba de Validación MD5
        run: |
          curl -s -X POST http://localhost/validate-md5 \
            -H "Content-Type: application/json" \
            -d '{"data": 123, "md5": "202cb962ac59075b964b07152d234b70"}' | grep "202cb962ac59075b964b07152d234b70"